CREATE TABLE "Users" (
  "user_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "full_name" varchar,
  "email" varchar UNIQUE,
  "phone_number" varchar,
  "created_at" datetime
);

CREATE TABLE "Locations" (
  "location_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "latitude" decimal(9,6),
  "longitude" decimal(9,6),
  "city" varchar,
  "state_code" char(2)
);

CREATE TABLE "CriticalEvents" (
  "event_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "event_type" varchar,
  "severity_level" varchar,
  "event_datetime" datetime,
  "event_status" varchar,
  "source" varchar,
  "description" text,
  "reporter_user_id" int,
  "location_id" int
);

CREATE TABLE "Subscriptions" (
  "subscription_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "channels" varchar,
  "created_on" datetime,
  "user_id" int,
  "location_id" int
);

ALTER TABLE "CriticalEvents" ADD FOREIGN KEY ("reporter_user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "CriticalEvents" ADD FOREIGN KEY ("location_id") REFERENCES "Locations" ("location_id");

ALTER TABLE "Subscriptions" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("user_id");

ALTER TABLE "Subscriptions" ADD FOREIGN KEY ("location_id") REFERENCES "Locations" ("location_id");
